name: Update README Table
on:
  push:
    paths:
      - 'problems.csv' # Jab bhi CSV change hogi, ye chalega

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Run Update Script
        run: python update_table.py
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Auto-update README table" || echo "No changes to commit"
          git push
          
